<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BarSchnoor.Entidades\BarSchnoor.Entidades.csproj" />
    <ProjectReference Include="..\BarSchnoor.Infra\BarSchnoor.Infra.csproj" />
  </ItemGroup>

</Project>